### ISSUE TITLE
QED roadmap

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#112]
Let's actually make an issue to summarize the QED development (i.e. the actual implementation of QED evolution in EKO), while the old #23 will keep serving the purpose of collecting ideas and related items.

- [x] unified basis implementation #89 
- [x] anomalous dimensions implementation #111
- [x] running of the couplings #115 
  - [x] specify orders in the runcards, proposal `PTO: n`  -> `order: {qcd: ns, qed: n}` such that we have an unambiguous PineAPPL compatible name (instead of a weird acronym...)
- [x] DGLAP solutions #135 
- [ ] and document them #211 
- [x] matching conditions upgrade
  - even if we have no QED matching conditions (to be verified at level of logs of mass over matching scale ratios) we still have to implement the existing ones in the unified basis
  - the easiest is to just apply the rotation after defining them in QCD evolution basis

**Comment by felixhekhorn** [comment]
@niclaurenti how about the matching? is this taken care of? if so, please tick - and then I'd say we can close this since the only left item is an issue on its own

**Comment by niclaurenti** [comment]
> @niclaurenti how about the matching? is this taken care of? if so, please tick - and then I'd say we can close this since the only left item is an issue on its own

Yes they are implemented (there is also a tex file in the extras)

**Comment by AleCandido** [comment]
Can we close this issue?
