### ISSUE TITLE
Oxidation roadmap

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#383]
- [x] ad.u.s.as1 #189 
- [ ] ad.u.s.{as2,as3} #369 
- [ ] ome.u.s.as1 and ome.u.s.as2 + VFNS
- [ ] recover SV
- [ ] ad.p.s.*
- [ ] recover solution methods
- [ ] ad.u.s.as4 and ad.u.s.as4.fhmruvv
- [ ] ad.u.s.*aem* + QED
- [ ] ad.u.t.*
- [ ] ome.u.s.as4
- [ ] anything left
